header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: KubeArmor
    content: |
      Copyright 2021 Authors of KubeArmor
      SPDX-License-Identifier: Apache-2.0

  paths:
    - "**/*.go"
    - "**/*.sh"
    - "**/Dockerfile"
    - "**/Makefile"

  paths-ignore:
    - ".travis/*"
    - "protobuf/*"

  comment: on-failure

dependency:
  files:
    - go.mod
