---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-security-kubearmor-com-v1-kubearmordefaultpolicy
  failurePolicy: Fail
  name: vkubearmordefaultpolicy.kb.io
  rules:
  - apiGroups:
    - security.kubearmor.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kubearmordefaultpolicies
  sideEffects: None
