//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 Authors of KubeArmor

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArmorDefaultPolicy) DeepCopyInto(out *KubeArmorDefaultPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArmorDefaultPolicy.
func (in *KubeArmorDefaultPolicy) DeepCopy() *KubeArmorDefaultPolicy {
	if in == nil {
		return nil
	}
	out := new(KubeArmorDefaultPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeArmorDefaultPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArmorDefaultPolicyList) DeepCopyInto(out *KubeArmorDefaultPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeArmorDefaultPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArmorDefaultPolicyList.
func (in *KubeArmorDefaultPolicyList) DeepCopy() *KubeArmorDefaultPolicyList {
	if in == nil {
		return nil
	}
	out := new(KubeArmorDefaultPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeArmorDefaultPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArmorDefaultPolicySpec) DeepCopyInto(out *KubeArmorDefaultPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArmorDefaultPolicySpec.
func (in *KubeArmorDefaultPolicySpec) DeepCopy() *KubeArmorDefaultPolicySpec {
	if in == nil {
		return nil
	}
	out := new(KubeArmorDefaultPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeArmorDefaultPolicyStatus) DeepCopyInto(out *KubeArmorDefaultPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeArmorDefaultPolicyStatus.
func (in *KubeArmorDefaultPolicyStatus) DeepCopy() *KubeArmorDefaultPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(KubeArmorDefaultPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
