name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: go workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check module vendoring
        run: |
          go mod tidy
          test -z "$(git status --porcelain)" || (git diff;git status;echo "please run 'go mod tidy', and submit your changes"; exit 1)
        working-directory: KubeArmor

      - name: Build bcc
        run: |
          set -x
          sudo apt-get update
          # Use release 9 of llvm etc. - later versions have an unfixed
          # bug on Ubuntu:
          # https://github.com/iovisor/bcc/issues/2915
          sudo apt-get -y install bison build-essential cmake flex git libelf-dev libfl-dev libedit-dev libllvm9 llvm-9-dev libclang-9-dev python zlib1g-dev
          pushd /tmp
          git clone --depth 1 --branch v0.20.0 https://github.com/iovisor/bcc.git
          mkdir -p bcc/build; cd bcc/build
          # Symlink /usr/lib/llvm to avoid "Unable to find clang libraries"
          # The directory appears only to be created when installing the
          # virtual llvm-dev package.
          # https://github.com/iovisor/bcc/issues/492
          sudo ln -s /usr/lib/llvm-9 /usr/local/llvm
          cmake ..
          make
          sudo make install
          popd

      - name: Build
        run: make build
        working-directory: KubeArmor
        env:
          GOPATH: /home/runner/go

      - name: test
        run: make testall
        working-directory: KubeArmor

      - name: Clean modcache
        run: go clean -modcache

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: KubeArmor
