name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.16", "1.15", "1.14", "1.13"]
    name: go workflows ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check module vendoring
        run: |
          cd KubeArmor
          go mod tidy
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy', and submit your changes";git status;git diff; exit 1)

      - name: Build bcc
        run: |
          set -x
          sudo apt-get update
          # Use release 9 of llvm etc. - later versions have an unfixed
          # bug on Ubuntu:
          # https://github.com/iovisor/bcc/issues/2915
          sudo apt-get -y install bison build-essential cmake flex git libelf-dev libfl-dev libedit-dev libllvm9 llvm-9-dev libclang-9-dev python zlib1g-dev
          pushd /tmp
          git clone --depth 1 --branch v0.20.0 https://github.com/iovisor/bcc.git
          mkdir -p bcc/build; cd bcc/build
          # Symlink /usr/lib/llvm to avoid "Unable to find clang libraries"
          # The directory appears only to be created when installing the
          # virtual llvm-dev package.
          # https://github.com/iovisor/bcc/issues/492
          sudo ln -s /usr/lib/llvm-9 /usr/local/llvm
          cmake ..
          make
          sudo make install
          popd

      - name: Build KubeArmor
        run: make build
        working-directory: KubeArmor
        env:
          GOPATH: /home/runner/go

      - name: Test KubeArmor
        run: make testall
        working-directory: KubeArmor

      - name: Coverage KubeArmor
        run: sudo -E env "PATH=$PATH" go test -race -covermode=atomic ./...
        working-directory: KubeArmor

      - name: Clean modcache
        if: ${{ always() }}
        run: go clean -modcache
        working-directory: KubeArmor

      - name: Lint
        if: ${{ always() }}
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: KubeArmor
