name: Go Related Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4052245BD4284CDD
          echo "deb https://repo.iovisor.org/apt/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/iovisor.list
          sudo apt-get update
          sudo apt-get install bcc-tools libbcc-examples linux-headers-$(uname -r)

      - name: debug
        run: cd KubeArmor && make build
        env:
          GOPATH: /home/runner/go
  # mod:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16
  #     - name: Check module vendoring
  #       run: |
  #         cd KubeArmor
  #         go mod tidy
  #         test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         working-directory: KubeArmor
  # vet:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16
  #     - name: Vet
  #       run: cd KubeArmor && go vet .
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16
  #     - name: Test
  #       run: cd KubeArmor && make testall
  #       env:
  #         GOPATH: /home/runner/go
