on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'master'

name: Latest version release

jobs:
  build:
    name: Create KubeArmor Release - Latest
    if: github.repository == 'kubearmor/KubeArmor'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout KubeArmor code
        uses: actions/checkout@v2

      - name: Generate KubeArmor artifacts
        run: ./KubeArmor/build/build_kubearmor.sh

      - name: Run KubeArmor tests
        run: ./contribution/self-managed-k8s/setup.sh && ./tests/go-test-kubearmor-local.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push KubeArmor images to Docker
        run: ./KubeArmor/build/push_kubearmor.sh
